const CRISTMAS_BASIC_DISCOUNT = 1000;
const CRISTMAS_ADDITIONAL_DISCOUNT = 100;

const DAY_OF_WEEK_DISCOUNT = 2023;

export {
  CRISTMAS_BASIC_DISCOUNT,
  CRISTMAS_ADDITIONAL_DISCOUNT,
  DAY_OF_WEEK_DISCOUNT,
};
