const MIN_RANGE_DATE = 1;
const MAX_RANGE_DATE = 31;

const INDEX_MENU_NAME = 0;
const INDEX_MENU_PRICE = 1;

const MIN_GIFT_MENU_APPLIED_PRICE = 120000;

export {
  MAX_RANGE_DATE,
  MIN_RANGE_DATE,
  INDEX_MENU_NAME,
  INDEX_MENU_PRICE,
  MIN_GIFT_MENU_APPLIED_PRICE,
};
