const FIRST_SEPARATE_TOKEN = ",";
const SECOND_SPPARATE_TOKEN = "-";

const MIN_RANGE_DATE = 1;
const MAX_RANGE_DATE = 31;

const INDEX_MENU_NAME = 0;
const INDEX_MENU_PRICE = 1;

const MIN_GIFT_MENU_APPLIED_PRICE = 120000;

const MIN_APPLICABLE_PRICE = 10000;

const MIN_ORDER_NUMBER = 1;
const MAX_ORDER_NUMBER = 20;

export {
  FIRST_SEPARATE_TOKEN,
  SECOND_SPPARATE_TOKEN,
  MAX_RANGE_DATE,
  MIN_RANGE_DATE,
  INDEX_MENU_NAME,
  INDEX_MENU_PRICE,
  MIN_GIFT_MENU_APPLIED_PRICE,
  MIN_APPLICABLE_PRICE,
  MIN_ORDER_NUMBER,
  MAX_ORDER_NUMBER,
};
